apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-db-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-mongo
  template:
    metadata:
      labels:
        app: todo-app-mongo
    spec:
      containers:
        - name: mongo-container
          image: mongo
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 27017
